### ISSUE TITLE
Fix sparks eventlogdir config accepts only absolute path

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/spotguide-spark#9]
Using the eventlogdir config like this 
```
--conf spark.eventLog.dir="s3a://baluchicken-test-spark-b1/" 
```
Causes:
```Error initializing SparkContext.
java.lang.IllegalArgumentException: path must be absolute
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at org.apache.hadoop.fs.s3a.s3guard.PathMetadata.<init>(PathMetadata.java:68)
    at org.apache.hadoop.fs.s3a.s3guard.PathMetadata.<init>(PathMetadata.java:60)
    at org.apache.hadoop.fs.s3a.s3guard.PathMetadata.<init>(PathMetadata.java:56)
    at org.apache.hadoop.fs.s3a.s3guard.S3Guard.putAndReturn(S3Guard.java:149)
    at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:2148)
    at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:2088)
    at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:100)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:522)
    at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
    at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:934)
    at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:925)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:925)
    at org.apache.spark.examples.SparkPi$.main(SparkPi.scala:31)
    at org.apache.spark.examples.SparkPi.main(SparkPi.scala)
```

**Comment by baluchicken** [comment]
This one is fixed by using two // instead of / at the end of the bucket path.
--conf spark.eventLog.dir="s3a://baluchicken-test-spark-b1//"
